server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/studentsdb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env